export const AppState = {
  layers: {
    // * ====================== CADASTRE ======================
    cad_boundary: {
      id: "cad-layer-boundary",
      name: "CAD Boundary",
      loaded: false,
      data: null,
      leafletLayer: null,
      checked: true,
      url: "data/geojson/cadastre/CAR_CAD_Boundary.geojson",
      style: {
        color: "#3b82f6",
        weight: 3,
        fillOpacity: 0,
      },
    },
    cad_province: {
      id: "cad-layer-province",
      name: "CAD Provinces",
      loaded: false,
      data: null,
      leafletLayer: null,
      checked: false,
      url: "data/geojson/cadastre/CAR_CAD_Provincial_Boundary.geojson",
      style: {
        color: "#06b6d4",
        weight: 2,
        fillOpacity: 0.1,
        fillColor: "#06b6d4",
      },
    },
    cad_municipality: {
      id: "cad-layer-municipality",
      name: "CAD Municipalities",
      loaded: false,
      data: null,
      leafletLayer: null,
      checked: false,
      url: "data/geojson/cadastre/CAR_CAD_Municipal_Boundary.geojson",
      style: {
        color: "#10b981",
        weight: 1,
        fillOpacity: 0.08,
        fillColor: "#10b981",
      },
    },
    // * === Other Layers ===
    cad_annual_crop: {
      id: "cad-layer-annual_crop",
      name: "CAR Cadastre Annual Crop",
      loaded: false,
      data: null,
      leafletLayer: null,
      checked: false,
      url: "data/geojson/cadastre/CAR_Annual_Crop_2025.geojson",
      style: {
        color: "#FEFAC2",
        weight: 1,
        fillOpacity: 1,
        fillColor: "#FEFAC2",
      },
    },
    cad_brush_shrubs: {
      id: "cad-layer-brush_shrubs",
      name: "CAR Cadastre Brush Shrubs",
      loaded: false,
      data: null,
      leafletLayer: null,
      checked: false,
      url: "data/geojson/cadastre/CAR_Brush_Shrubs_2025.geojson",
      style: {
        color: "#FEFAC2",
        weight: 1,
        fillOpacity: 1,
        fillColor: "#FEFAC2",
      },
    },
    cad_built_up: {
      id: "cad-layer-built_up",
      name: "CAR Cadastre Built Up",
      loaded: false,
      data: null,
      leafletLayer: null,
      checked: false,
      url: "data/geojson/cadastre/CAR_Built-Up_2025.geojson",
      style: {
        color: "#FF0000",
        weight: 1,
        fillOpacity: 1,
        fillColor: "#FF0000",
      },
    },
    cad_closed_forest: {
      id: "cad-layer-closed_forest",
      name: "CAR Cadastre Closed Forest",
      loaded: false,
      data: null,
      leafletLayer: null,
      checked: false,
      url: "data/geojson/cadastre/CAR_Closed_Forest_2025.geojson",
      style: {
        color: "#016300",
        weight: 1,
        fillOpacity: 1,
        fillColor: "#016300",
      },
    },
    cad_open_forest: {
      id: "cad-layer-open_forest",
      name: "CAR Cadastre Open Forest",
      loaded: false,
      data: null,
      leafletLayer: null,
      checked: false,
      url: "data/geojson/cadastre/CAR_Open_Forest_2025.geojson",
      style: {
        color: "#02DB00",
        weight: 1,
        fillOpacity: 1,
        fillColor: "#02DB00",
      },
    },
    cad_open_barren: {
      id: "cad-layer-open_barren",
      name: "CAR Cadastre Open Barren",
      loaded: false,
      data: null,
      leafletLayer: null,
      checked: false,
      url: "data/geojson/cadastre/CAR_Open_Barren_2025.geojson",
      style: {
        color: "#D2D2D2",
        weight: 1,
        fillOpacity: 1,
        fillColor: "#D2D2D2",
      },
    },
    cad_grassland: {
      id: "cad-layer-grassland",
      name: "CAR Cadastre Grassland",
      loaded: false,
      data: null,
      leafletLayer: null,
      checked: false,
      url: "data/geojson/cadastre/CAR_Grassland_2025.geojson",
      style: {
        color: "#974749",
        weight: 1,
        fillOpacity: 1,
        fillColor: "#974749",
      },
    },
    cad_perennial_crop_2025: {
      id: "cad-layer-perennial_crop_2025",
      name: "CAR Cadastre Perennial Crop 2025",
      loaded: false,
      data: null,
      leafletLayer: null,
      checked: false,
      url: "data/geojson/cadastre/CAR_Perennial_Crop_2025.geojson",
      style: {
        color: "#e49a56",
        weight: 1,
        fillOpacity: 1,
        fillColor: "#e49a56",
      },
    },
    cad_fishpond: {
      id: "cad-layer-fishpond",
      name: "CAR Cadastre Fishpond",
      loaded: false,
      data: null,
      leafletLayer: null,
      checked: false,
      url: "data/geojson/cadastre/CAR_Fishpond_2025.geojson",
      style: {
        color: "#0081fe",
        weight: 1,
        fillOpacity: 1,
        fillColor: "#0081fe",
      },
    },
    cad_inland_water: {
      id: "cad-layer-inland_water",
      name: "CAR Cadastre Inland Water",
      loaded: false,
      data: null,
      leafletLayer: null,
      checked: false,
      url: "data/geojson/cadastre/CAR_Inland_Water_2025.geojson",
      style: {
        color: "#281F94",
        weight: 1,
        fillOpacity: 1,
        fillColor: "#281F94",
      },
    },
    cad_a_and_d: {
      id: "cad-layer-a_and_d",
      name: "CAR Cadastre A and D",
      loaded: false,
      data: null,
      leafletLayer: null,
      checked: false,
      url: "data/geojson/cadastre/CAR_A_and_D.geojson",
      style: {
        color: "#FF7F7F",
        weight: 1,
        fillOpacity: 1,
        fillColor: "#FF7F7F",
      },
    },
    cad_forestland: {
      id: "cad-layer-forestland",
      name: "CAR Cadastre Forestland",
      loaded: false,
      data: null,
      leafletLayer: null,
      checked: false,
      url: "data/geojson/cadastre/CAR_Forestland.geojson",
      style: {
        color: "#4CE600",
        weight: 1,
        fillOpacity: 1,
        fillColor: "#4CE600",
      },
    },
    cad_climate: {
      id: "cad-layer-climate",
      name: "CAR Cadastre Climate",
      loaded: false,
      data: null,
      leafletLayer: null,
      checked: false,
      url: "data/geojson/cadastre/CAR_Climate.geojson",
      colorField: "CODE",
      style: {
        weight: 1,
        fillOpacity: 1,
      },
      codeColors: {
        "1st Type": "#D74042",
        "2nd Type": "#7C76D8",
        "3rd Type": "#E1E1E1",
        "4th Type": "#38C238",
      },
    },
    cad_slope: {
      id: "cad-layer-slope",
      name: "CAR Cadastre Slope",
      loaded: false,
      data: null,
      leafletLayer: null,
      checked: false,
      url: "data/geojson/cadastre/CAR_CAD_Slope.geojson",
      colorField: "SL_Cate",
      style: {
        weight: 1,
        fillOpacity: 1,
      },
      codeColors: {
        "0 - 8": "#50A823",
        "8 - 18": "#8BD100",
        "18 - 30": "#FFFF00",
        "30 - 50": "#FF9A36",
        "Above 50": "#FF4A4A",
      },
    },
    cad_erosion: {
      id: "cad-layer-erosion",
      name: "CAR Cadastre Erosion",
      loaded: false,
      data: null,
      leafletLayer: null,
      checked: false,
      url: "data/geojson/cadastre/CAR_Erosion.geojson",
      colorField: "Erosion",
      style: {
        weight: 1,
        fillOpacity: 1,
      },
      codeColors: {
        "No Apparent Erosion": "#FFFFBF",
        "Slight Erosion": "#CFB667",
        "Moderate Erosion": "#A16A28",
        "Severe Erosion": "#732600",
        "Unclassified Erosion": "#E1E1E1",
        Reservoir: "#BFD9F2",
        River: "#FFFFFF",
      },
    },
    cad_geology: {
      id: "cad-layer-geology",
      name: "CAR Cadastre Geology",
      loaded: false,
      data: null,
      leafletLayer: null,
      checked: false,
      url: "data/geojson/cadastre/CAR_Geology.geojson",
      style: {
        color: "#341ff0",
        weight: 1,
        fillOpacity: 1,
        fillColor: "#341ff0",
      },
    },
    cad_flood_susceptibility: {
      id: "cad-layer-flood_susceptibility",
      name: "CAR Cadastre Flood Susceptibility",
      loaded: false,
      data: null,
      leafletLayer: null,
      checked: false,
      url: "data/geojson/cadastre/CAR_Flood_Susceptibility.geojson",
      colorField: "FloodSusc",
      style: {
        weight: 1,
        fillOpacity: 1,
      },
      codeColors: {
        LF: "#E8BEFF",
        MF: "#C500FF",
        HF: "#673FD0",
        VHF: "#003893",
      },
    },
    cad_fire_susceptibility: {
      id: "cad-layer-fire_susceptibility",
      name: "CAR Cadastre Fire Susceptibility",
      loaded: false,
      data: null,
      leafletLayer: null,
      checked: false,
      url: "data/geojson/cadastre/CAR_Fire_Susceptibility.geojson",
      colorField: "Risk_Class",
      style: {
        weight: 1,
        fillOpacity: 1,
      },
      codeColors: {
        VL: "#267300",
        L: "#55FF00",
        M: "#FFFF00",
        H: "#FFAA00",
        VH: "#FF0000",
      },
    },
    cad_landslide_susceptibility: {
      id: "cad-layer-landslide_susceptibility",
      name: "CAR Cadastre Landslide Susceptibility",
      loaded: false,
      data: null,
      leafletLayer: null,
      checked: false,
      url: "data/geojson/cadastre/CAR_Landslide_Susceptibility.geojson",
      colorField: "LndslideSu",
      style: {
        weight: 1,
        fillOpacity: 1,
      },
      codeColors: {
        DB: "#B2B2B2",
        MDF: "#FFAA00",
        LL: "#FFFF00",
        ML: "#4CE600",
        HL: "#FF0000",
        VHL: "#732600",
      },
    },
    // * ====================== NAMRIA ======================
    namria_boundary: {
      id: "namria-layer-boundary",
      name: "NAMRIA Boundary",
      loaded: false,
      data: null,
      leafletLayer: null,
      checked: false,
      url: "data/geojson/namria/CAR_NAMRIA_Boundary.geojson",
      style: {
        color: "#3b82f6",
        weight: 3,
        fillOpacity: 0,
      },
    },
    namria_province: {
      id: "namria_layer-province",
      name: "NAMRIA Provinces",
      loaded: false,
      data: null,
      leafletLayer: null,
      checked: false,
      url: "data/geojson/namria/CAR_NAMRIA_Provincial_Boundary.geojson",
      style: {
        color: "#06b6d4",
        weight: 2,
        fillOpacity: 0.1,
        fillColor: "#06b6d4",
      },
    },
    namria_municipality: {
      id: "namria_layer-municipality",
      name: "NAMRIA Municipalities",
      loaded: false,
      data: null,
      leafletLayer: null,
      checked: false,
      url: "data/geojson/namria/CAR_NAMRIA_Municipal_Boundary.geojson",
      style: {
        color: "#10b981",
        weight: 1.2,
        dashArray: "4, 4",
        fillOpacity: 0,
      },
    },
    // * === Other Layers ===
    namria_annual_crop: {
      id: "namria-layer-annual_crop",
      name: "CAR Namria Annual Crop",
      loaded: false,
      data: null,
      leafletLayer: null,
      checked: false,
      url: "data/geojson/namria/CAR_NAMRIA_AnnualCrop.geojson",
      style: {
        color: "#FEFAC2",
        weight: 1,
        fillOpacity: 1,
        fillColor: "#FEFAC2",
      },
    },
    namria_brush_shrubs: {
      id: "namria-layer-brush_shrubs",
      name: "CAR Namria Brush Shrubs",
      loaded: false,
      data: null,
      leafletLayer: null,
      checked: false,
      url: "data/geojson/namria/CAR_NAMRIA_BrushShrubs.geojson",
      style: {
        color: "#FEFAC2",
        weight: 1,
        fillOpacity: 1,
        fillColor: "#FEFAC2",
      },
    },
    namria_built_up: {
      id: "namria-layer-built_up",
      name: "CAR Namria Built Up",
      loaded: false,
      data: null,
      leafletLayer: null,
      checked: false,
      url: "data/geojson/namria/CAR_NAMRIA_BuiltUp.geojson",
      style: {
        color: "#FF0000",
        weight: 1,
        fillOpacity: 1,
        fillColor: "#FF0000",
      },
    },
    namria_closed_forest: {
      id: "namria-layer-closed_forest",
      name: "CAR Namria Closed Forest",
      loaded: false,
      data: null,
      leafletLayer: null,
      checked: false,
      url: "data/geojson/namria/CAR_NAMRIA_ClosedForest.geojson",
      style: {
        color: "#016300",
        weight: 1,
        fillOpacity: 1,
        fillColor: "#016300",
      },
    },
    namria_open_forest: {
      id: "namria-layer-open_forest",
      name: "CAR Namria Open Forest",
      loaded: false,
      data: null,
      leafletLayer: null,
      checked: false,
      url: "data/geojson/namria/CAR_NAMRIA_OpenForest.geojson",
      style: {
        color: "#02DB00",
        weight: 1,
        fillOpacity: 1,
        fillColor: "#02DB00",
      },
    },
    namria_open_barren: {
      id: "namria-layer-open_barren",
      name: "CAR Namria Open Barren",
      loaded: false,
      data: null,
      leafletLayer: null,
      checked: false,
      url: "data/geojson/namria/CAR_NAMRIA_OpenBarren.geojson",
      style: {
        color: "#D2D2D2",
        weight: 1,
        fillOpacity: 1,
        fillColor: "#D2D2D2",
      },
    },
    namria_grassland: {
      id: "namria-layer-grassland",
      name: "CAR Namria Grassland",
      loaded: false,
      data: null,
      leafletLayer: null,
      checked: false,
      url: "data/geojson/namria/CAR_NAMRIA_Grassland.geojson",
      style: {
        color: "#974749",
        weight: 1,
        fillOpacity: 1,
        fillColor: "#974749",
      },
    },
    namria_perennial_crop_2025: {
      id: "namria-layer-perennial_crop_2025",
      name: "CAR Namria Perennial Crop 2025",
      loaded: false,
      data: null,
      leafletLayer: null,
      checked: false,
      url: "data/geojson/namria/CAR_NAMRIA_Perrenial.geojson",
      style: {
        color: "#e49a56",
        weight: 1,
        fillOpacity: 1,
        fillColor: "#e49a56",
      },
    },
    namria_fishpond: {
      id: "namria-layer-fishpond",
      name: "CAR Namria Fishpond",
      loaded: false,
      data: null,
      leafletLayer: null,
      checked: false,
      url: "data/geojson/namria/CAR_NAMRIA_Fishpond.geojson",
      style: {
        color: "#0081fe",
        weight: 1,
        fillOpacity: 1,
        fillColor: "#0081fe",
      },
    },
    namria_inland_water: {
      id: "namria-layer-inland_water",
      name: "CAR Namria Inland Water",
      loaded: false,
      data: null,
      leafletLayer: null,
      checked: false,
      url: "data/geojson/namria/CAR_NAMRIA_Inland_Waters.geojson",
      style: {
        color: "#281F94",
        weight: 1,
        fillOpacity: 1,
        fillColor: "#281F94",
      },
    },
    namria_a_and_d: {
      id: "namria-layer-a_and_d",
      name: "CAR Namria A and D",
      loaded: false,
      data: null,
      leafletLayer: null,
      checked: false,
      url: "data/geojson/namria/CAR_NAMRIA_AnD.geojson",
      style: {
        color: "#FF7F7F",
        weight: 1,
        fillOpacity: 1,
        fillColor: "#FF7F7F",
      },
    },
    namria_forestland: {
      id: "namria-layer-forestland",
      name: "CAR Namria Forestland",
      loaded: false,
      data: null,
      leafletLayer: null,
      checked: false,
      url: "data/geojson/namria/CAR_NAMRIA_Forestland.geojson",
      style: {
        color: "#4CE600",
        weight: 1,
        fillOpacity: 1,
        fillColor: "#4CE600",
      },
    },
    namria_climate: {
      id: "namria-layer-climate",
      name: "CAR Namria Climate",
      loaded: false,
      data: null,
      leafletLayer: null,
      checked: false,
      url: "data/geojson/namria/CAR_NAMRIA_Climate.geojson",
      colorField: "CODE",
      style: {
        weight: 1,
        fillOpacity: 1,
      },
      codeColors: {
        "1st Type": "#D74042",
        "2nd Type": "#7C76D8",
        "3rd Type": "#E1E1E1",
        "4th Type": "#38C238",
      },
    },
    namria_slope: {
      id: "namria-layer-slope",
      name: "CAR Namria Slope",
      loaded: false,
      data: null,
      leafletLayer: null,
      checked: false,
      url: "data/geojson/namria/CAR_NAMRIA_Slope.geojson",
      colorField: "SL_Cate",
      style: {
        weight: 1,
        fillOpacity: 1,
      },
      codeColors: {
        "0 - 8": "#50A823",
        "8 - 18": "#8BD100",
        "18 - 30": "#FFFF00",
        "30 - 50": "#FF9A36",
        "Above 50": "#FF4A4A",
      },
    },
    namria_erosion: {
      id: "namria-layer-erosion",
      name: "CAR Namria Erosion",
      loaded: false,
      data: null,
      leafletLayer: null,
      checked: false,
      url: "data/geojson/namria/CAR_NAMRIA_Erosion.geojson",
      colorField: "DESCRIPT",
      style: {
        weight: 1,
        fillOpacity: 1,
      },
      codeColors: {
        "No Apparent Erosion": "#FFFFBF",
        "Slight Erosion": "#CFB667",
        "Moderate Erosion": "#A16A28",
        "Severe Erosion": "#732600",
        "Unclassified Erosion": "#E1E1E1",
        Reservoir: "#BFD9F2",
        River: "#FFFFFF",
      },
    },
    namria_flood_susceptibility: {
      id: "namria-layer-flood_susceptibility",
      name: "CAR Namria Flood Susceptibility",
      loaded: false,
      data: null,
      leafletLayer: null,
      checked: false,
      url: "data/geojson/namria/CAR_NAMRIA_FloodSusceptibility.geojson",
      colorField: "FloodSusc",
      style: {
        weight: 1,
        fillOpacity: 1,
      },
      codeColors: {
        LF: "#E8BEFF",
        MF: "#C500FF",
        HF: "#673FD0",
        VHF: "#003893",
      },
    },
    // ! Fire Susceptibility
    namria_landslide_susceptibility: {
      id: "namria-layer-landslide_susceptibility",
      name: "CAR Namria Landslide Susceptibility",
      loaded: false,
      data: null,
      leafletLayer: null,
      checked: false,
      url: "data/geojson/namria/CAR_NAMRIA_LandslideSusceptibility.geojson",
      colorField: "LndslideSu",
      style: {
        weight: 1,
        fillOpacity: 1,
      },
      codeColors: {
        DB: "#B2B2B2",
        MDF: "#FFAA00",
        LL: "#FFFF00",
        ML: "#4CE600",
        HL: "#FF0000",
        VHL: "#732600",
      },
    },
    // * ====================== COMMON ======================
    cad_ngp: {
      id: "cad_layer-ngp",
      name: "CAR NGP",
      loaded: false,
      data: null,
      leafletLayer: null,
      checked: false,
      url: "data/geojson/common/NGP_2011_2025.geojson",
      colorField: "YR_ESTAB",
      style: {
        weight: 1,
        fillOpacity: 1,
      },
      codeColors: {
        2011: "#FFFF00",
        2012: "#005CE6",
        2013: "#FF0000",
        2014: "#267300",
        2015: "#E69800",
        2016: "#C500FF",
        2017: "#19E802",
        2018: "#B5B35C",
        2020: "#A3E3ED",
        2021: "#FD7B33",
        2022: "#0225ED",
        2023: "#FF1493",
        2024: "#F5DEB3",
        2025: "#4B0082",
      },
    },
    namria_ngp: {
      id: "namria_layer-ngp",
      name: "CAR NGP",
      loaded: false,
      data: null,
      leafletLayer: null,
      checked: false,
      url: "data/geojson/common/NGP_2011_2025.geojson",
      colorField: "YR_ESTAB",
      style: {
        weight: 1,
        fillOpacity: 1,
      },
      codeColors: {
        2011: "#FFFF00",
        2012: "#005CE6",
        2013: "#FF0000",
        2014: "#267300",
        2015: "#E69800",
        2016: "#C500FF",
        2017: "#19E802",
        2018: "#B5B35C",
        2020: "#A3E3ED",
        2021: "#FD7B33",
        2022: "#0225ED",
        2023: "#FF1493",
        2024: "#F5DEB3",
        2025: "#4B0082",
      },
    },
    cad_tenurial_instrument: {
      id: "cad_layer-tenurial_instrument",
      name: "CAR Tenurial Instrument",
      loaded: false,
      data: null,
      leafletLayer: null,
      checked: false,
      url: "data/geojson/common/CAR_Tenurial_Instrument.geojson",
      style: {
        color: "#4CE600",
        weight: 1,
        fillOpacity: 1,
        fillColor: "#4CE600",
      },
    },
    namria_tenurial_instrument: {
      id: "namria_layer-tenurial_instrument",
      name: "CAR Tenurial Instrument",
      loaded: false,
      data: null,
      leafletLayer: null,
      checked: false,
      url: "data/geojson/common/CAR_Tenurial_Instrument.geojson",
      style: {
        color: "#4CE600",
        weight: 1,
        fillOpacity: 1,
        fillColor: "#4CE600",
      },
    },
    cad_pa: {
      id: "cad-layer-pa",
      name: "CAR Protected Areas",
      loaded: false,
      data: null,
      leafletLayer: null,
      checked: false,
      url: "data/geojson/common/CAR_Legislated_PA.geojson",
      style: {
        color: "#fffb00",
        weight: 1,
        fillOpacity: 1,
        fillColor: "#fffb00",
      },
    },
    namria_pa: {
      id: "namria-layer-pa",
      name: "CAR Protected Areas",
      loaded: false,
      data: null,
      leafletLayer: null,
      checked: false,
      url: "data/geojson/common/CAR_Legislated_PA.geojson",
      style: {
        color: "#fffb00",
        weight: 1,
        fillOpacity: 1,
        fillColor: "#fffb00",
      },
    },
  },
  importedLayers: [],
  pendingLayerCount: 0,
  selectedBoundary: null,
  activeProvinceSlopeKey: null,
};
